import React, { useState } from "react";
import { ComponentPanel } from "./ComponentPanel";
import { interpretCommand } from "./ai/interpretCommand";
import { CanvasRenderer } from "./CanvasRenderer";

/**
 * BuilderApp
 * ----------
 * This is the main UI shell for your AI-driven builder.
 * It now uses:
 *  - TWIN PRIME / PUBLIC via the interpreter
 *  - CanvasRenderer for real UI rendering
 *  - History panel for transparency
 */

export default function BuilderApp() {
  const [components, setComponents] = useState([]);
  const [screens, setScreens] = useState([]);
  const [app, setApp] = useState(null);
  const [history, setHistory] = useState([]);

  async function handleAICommand(command) {
    // Record user command
    setHistory((prev) => [...prev, { role: "user", text: command }]);

    // Run through interpreter
    const result = await interpretCommand(command);

    // Record AI interpretation
    setHistory((prev) => [
      ...prev,
      {
        role: "ai",
        text: `Interpreted as ${result.structureType} (${result.intent})`
      }
    ]);

    // Handle structure types
    if (result.structureType === "component") {
      setComponents((prev) => [...prev, ...result.components]);
    }

    if (result.structureType === "screen") {
      setScreens((prev) => [...prev, result.screen]);
    }

    if (result.structureType === "app") {
      setApp(result.app);
      setScreens(result.app.screens || []);
      setComponents([]); // app-level replaces component-level
    }
  }

  return (
    <div style={{ display: "flex", height: "100%", width: "100%" }}>
      {/* LEFT PANEL: AI Input + History */}
      <aside
        style={{
          width: 300,
          borderRight: "1px solid #ddd",
          background: "#fafafa",
          overflowY: "auto"
        }}
      >
        <ComponentPanel onAICommand={handleAICommand} />

        <div style={{ padding: 16 }}>
          <h4>History</h4>
          {history.map((entry, i) => (
            <div
              key={i}
              style={{
                marginBottom: 8,
                padding: 8,
                background: entry.role === "user" ? "#eef" : "#efe",
                borderRadius: 4
              }}
            >
              <strong>{entry.role === "user" ? "You" : "AI"}:</strong>{" "}
              {entry.text}
            </div>
          ))}
        </div>
      </aside>

      {/* CANVAS */}
      <main
        style={{
          flex: 1,
          background: "#fff",
          padding: 24,
          overflow: "auto"
        }}
      >
        <h2>Canvas</h2>

        {/* APP LEVEL */}
        {app && (
          <div
            style={{
              padding: 16,
              marginBottom: 24,
              border: "2px solid #4a6cf7",
              borderRadius: 6
            }}
          >
            <h3>{app.name}</h3>
            <p style={{ opacity: 0.7 }}>App-level structure generated by AI</p>

            {app.screens?.map((screen) => (
              <div
                key={screen.id}
                style={{
                  padding: 12,
                  marginBottom: 16,
                  border: "1px solid #ccc",
                  borderRadius: 4
                }}
              >
                <strong>{screen.name}</strong>
                <CanvasRenderer components={screen.components || []} />
              </div>
            ))}
          </div>
        )}

        {/* SCREEN LEVEL (when no app exists) */}
        {!app && screens.length > 0 && (
          <div style={{ marginBottom: 24 }}>
            <h3>Screens</h3>
            {screens.map((screen) => (
              <div
                key={screen.id}
                style={{
                  padding: 12,
                  marginBottom: 12,
                  border: "1px solid #ccc",
                  borderRadius: 4
                }}
              >
                <strong>{screen.name}</strong>
                <CanvasRenderer components={screen.components || []} />
              </div>
            ))}
          </div>
        )}

        {/* COMPONENT LEVEL (when no screens or app exist) */}
        {!app && screens.length === 0 && components.length > 0 && (
          <div>
            <h3>Components</h3>
            <CanvasRenderer components={components} />
          </div>
        )}

        {/* EMPTY STATE */}
        {!app && screens.length === 0 && components.length === 0 && (
          <p style={{ color: "#888" }}>
            Describe what you want to build.  
            The AI will generate the app here.
          </p>
        )}
      </main>
    </div>
  );
}
