export function builderCoreTemplate(appName) {
  return {
    "index.html": `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${appName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>`,

    "src/main.jsx": `import React from "react";
import { createRoot } from "react-dom/client";
import App from "./App";
import "./styles.css";

createRoot(document.getElementById("root")).render(<App />);
`,

    "src/App.jsx": `export default function App() {
  return (
    <div style={{ padding: 40 }}>
      <h1>${appName}</h1>
      <p>This app builder was generated by Blue Lotus.</p>
    </div>
  );
}
`,

    "src/styles.css": `body {
  margin: 0;
  font-family: system-ui, sans-serif;
  background: #020617;
  color: #e2e8f0;
}`
  };
}
