// frontend/src/runtime/LivePreview.js

/**
 * LivePreview
 * -----------------------------------------
 * Renders the user's app in real time using
 * the preview payload generated by the backend.
 *
 * This component NEVER executes user code.
 * It only renders a safe, structured preview.
 */

import React from "react";
import AppRenderer from "./AppRenderer.jsx";

export default function LivePreview({ preview }) {
  if (!preview) {
    return (
      <div style={styles.empty}>
        <p style={styles.emptyText}>No preview available</p>
      </div>
    );
  }

  const { pages, name } = preview;

  return (
    <div style={styles.container}>
      <div style={styles.header}>
        <h2 style={styles.title}>{name} — Live Preview</h2>
      </div>

      <div style={styles.previewArea}>
        <AppRenderer pages={pages} />
      </div>
    </div>
  );
}

const styles = {
  container: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    background: "#f8f9fa",
  },
  header: {
    padding: "12px 16px",
    borderBottom: "1px solid #ddd",
    background: "#ffffff",
  },
  title: {
    margin: 0,
    fontSize: "18px",
    fontWeight: 600,
    color: "#333",
  },
  previewArea: {
    flex: 1,
    overflow: "auto",
    padding: "16px",
  },
  empty: {
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "#fafafa",
    border: "1px dashed #ccc",
  },
  emptyText: {
    color: "#777",
    fontSize: "16px",
  },
};
