import React, { useState, useEffect } from 'react';
import { 
  Leaf, 
  Sprout, 
  Crown, 
  Plus, 
  Send, 
  Terminal, 
  Globe, 
  Github, 
  ChevronRight, 
  Loader2,
  CheckCircle2,
  AlertCircle
} from 'lucide-react';

// Plans Array (Kept your design)
const plans = [
  { id: 'sprout', name: 'Lotus Sprout', icon: Leaf, cost: '5 Velocity', desc: 'Single component generation' },
  { id: 'bloom', name: 'Lotus Bloom', icon: Sprout, cost: '15 Velocity', desc: 'Full page architecture' },
  { id: 'crown', name: 'Lotus Crown', icon: Crown, cost: '50 Velocity', desc: 'Multi-page application suite' }
];

export default function App() {
  const [view, setView] = useState('garden');
  const [selectedPlan, setSelectedPlan] = useState(null);
  const [prompt, setPrompt] = useState('');
  const [logs, setLogs] = useState([]);
  const [isCultivating, setIsCultivating] = useState(false);
  const [generatedFiles, setGeneratedFiles] = useState(null);
  const [deployedUrl, setDeployedUrl] = useState(null);

  const addLog = (message, type = 'info') => {
    setLogs(prev => [...prev, { id: Date.now(), message, type }]);
  };

  // Logic Upgrade: The Brain Connection
  const handleBeginCultivation = async () => {
    if (!prompt) return;
    setIsCultivating(true);
    setView('forge');
    setLogs([]);
    addLog('Initializing Sovereign Architect...', 'info');

    try {
      const response = await fetch('/api/twin', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt, plan: selectedPlan?.id }),
      });

      const data = await response.json();

      if (data.ok) {
        addLog('Blueprint successfully generated by TWIN.', 'success');
        setGeneratedFiles(data.files);
        addLog(`Architecture complete: ${data.files.length} files synthesized.`, 'info');
      } else {
        throw new Error(data.error || 'Cultivation failed');
      }
    } catch (err) {
      addLog(`Error: ${err.message}`, 'error');
    } finally {
      setIsCultivating(false);
    }
  };

  // Logic Upgrade: The Manifestation (GitHub/Vercel)
  const handleManifest = async () => {
    if (!generatedFiles) return;
    addLog('Opening Sovereign Gate to GitHub...', 'info');
    
    try {
      const repoName = `lotus-build-${Date.now()}`;
      const response = await fetch('/api/publish', { // Fixed endpoint
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ files: generatedFiles, repoName }),
      });

      const result = await response.json();

      if (result.success) {
        addLog('Code successfully manifested on GitHub!', 'success');
        setDeployedUrl(result.repoUrl);
      } else {
        throw new Error(result.error);
      }
    } catch (err) {
      addLog(`Manifestation failed: ${err.message}`, 'error');
    }
  };

  return (
    <div className="min-h-screen bg-[#020617] text-slate-200 font-sans selection:bg-cyan-500/30">
      {/* HEADER (Your Design) */}
      <nav className="border-b border-white/5 bg-slate-950/50 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3 group cursor-pointer" onClick={() => setView('garden')}>
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-cyan-500 to-blue-600 flex items-center justify-center shadow-[0_0_15px_rgba(6,182,212,0.4)] group-hover:scale-110 transition-transform">
              <Leaf className="w-5 h-5 text-white" />
            </div>
            <span className="font-bold tracking-tight text-lg text-white">Blue Lotus Clean</span>
          </div>
          <div className="flex items-center gap-6">
            <div className="flex items-center gap-2 px-3 py-1 bg-white/5 rounded-full border border-white/10">
              <div className="w-2 h-2 rounded-full bg-cyan-500 animate-pulse" />
              <span className="text-xs font-medium text-slate-400">System Ready</span>
            </div>
          </div>
        </div>
      </nav>

      <main className="max-w-7xl mx-auto px-6 py-12">
        {view === 'garden' ? (
          <div className="space-y-12 animate-in fade-in slide-in-from-bottom-4 duration-700">
            {/* GARDEN VIEW (Your Icons & Layout) */}
            <header className="max-w-2xl">
              <h2 className="text-4xl font-bold text-white mb-4">Blue Lotus Garden</h2>
              <p className="text-slate-400 text-lg leading-relaxed">Select a plan to begin cultivating your sovereign digital asset.</p>
            </header>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {plans.map((plan) => (
                <button
                  key={plan.id}
                  onClick={() => setSelectedPlan(plan)}
                  className={`relative group p-6 rounded-2xl border transition-all text-left ${
                    selectedPlan?.id === plan.id 
                    ? 'bg-cyan-500/10 border-cyan-500/50 shadow-[0_0_30px_rgba(6,182,212,0.1)]' 
                    : 'bg-slate-900/50 border-white/5 hover:border-white/10'
                  }`}
                >
                  <plan.icon className={`w-8 h-8 mb-4 ${selectedPlan?.id === plan.id ? 'text-cyan-400' : 'text-slate-400'}`} />
                  <h3 className="font-bold text-white text-lg mb-1">{plan.name}</h3>
                  <p className="text-sm text-slate-400 mb-4">{plan.desc}</p>
                  <span className="text-xs font-bold text-cyan-500 uppercase tracking-widest">{plan.cost}</span>
                </button>
              ))}
            </div>

            {selectedPlan && (
              <div className="bg-slate-900/40 border border-white/5 rounded-3xl p-8 backdrop-blur-sm animate-in zoom-in-95 duration-300">
                <textarea
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  placeholder="Describe the application you want to manifest..."
                  className="w-full h-40 bg-transparent text-xl text-white placeholder:text-slate-600 border-none focus:ring-0 resize-none"
                />
                <div className="flex justify-end pt-4 border-t border-white/5">
                  <button
                    onClick={handleBeginCultivation}
                    className="group px-8 py-4 bg-white text-slate-950 rounded-full font-bold flex items-center gap-2 hover:bg-cyan-400 transition-colors"
                  >
                    Begin Cultivation
                    <ChevronRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                  </button>
                </div>
              </div>
            )}
          </div>
        ) : (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 h-[calc(100vh-12rem)] animate-in fade-in duration-500">
            {/* FORGE VIEW (Kept your Console UI) */}
            <div className="flex flex-col bg-slate-950 rounded-2xl border border-white/5 overflow-hidden">
              <div className="p-4 border-b border-white/5 bg-slate-900/50 flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Terminal className="w-4 h-4 text-cyan-500" />
                  <span className="text-xs font-bold uppercase tracking-widest text-slate-400">Forge Console</span>
                </div>
                {deployedUrl && (
                  <a href={deployedUrl} target="_blank" className="text-xs text-cyan-400 hover:underline flex items-center gap-1">
                    <Github className="w-3 h-3" /> View Source
                  </a>
                )}
              </div>
              
              <div className="flex-1 p-6 font-mono text-sm space-y-3 overflow-y-auto">
                {logs.map(log => (
                  <div key={log.id} className="flex gap-3">
                    <span className="text-slate-600">[{new Date(log.id).toLocaleTimeString([], {hour12: false})}]</span>
                    <span className={
                      log.type === 'success' ? 'text-emerald-400' : 
                      log.type === 'error' ? 'text-rose-400' : 'text-cyan-400'
                    }>
                      {log.type === 'success' ? '✓' : log.type === 'error' ? '×' : '→'} {log.message}
                    </span>
                  </div>
                ))}
                {isCultivating && (
                  <div className="flex items-center gap-2 text-slate-400 italic">
                    <Loader2 className="w-3 h-3 animate-spin" />
                    Processing blueprint...
                  </div>
                )}
              </div>

              <div className="p-6 border-t border-white/5">
                <button
                  disabled={!generatedFiles || isCultivating}
                  onClick={handleManifest}
                  className="w-full py-4 bg-cyan-600 hover:bg-cyan-500 disabled:opacity-50 disabled:hover:bg-cyan-600 text-white rounded-xl font-bold flex items-center justify-center gap-2 transition-all shadow-lg shadow-cyan-500/20"
                >
                  {isCultivating ? <Loader2 className="w-5 h-5 animate-spin" /> : <Globe className="w-5 h-5" />}
                  Manifest Sovereign Blueprint
                </button>
              </div>
            </div>

            {/* PREVIEW (Placeholder for your design) */}
            <div className="bg-white/5 rounded-2xl border border-white/5 flex items-center justify-center relative overflow-hidden group">
              <div className="absolute inset-0 bg-gradient-to-br from-cyan-500/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />
              <div className="text-center p-8">
                <Loader2 className="w-12 h-12 text-slate-700 mx-auto mb-4 animate-spin" />
                <p className="text-slate-500 font-medium tracking-tight">Awaiting architecture manifestation...</p>
              </div>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
