import React, { useState, useEffect } from 'react';

const animationKeyframes = `
  @keyframes scanline { 0% { bottom: 100%; } 100% { bottom: 0%; } }
  @keyframes fadeRender { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }
`;

function App() {
  const [view, setView] = useState('landing'); 
  const [booting, setBooting] = useState(false);
  const [bootProgress, setBootProgress] = useState(0);
  const [isGenerating, setIsGenerating] = useState(false);
  const [previewContent, setPreviewContent] = useState(null);
  const [consoleLog, setConsoleLog] = useState(["// TWIN_CORE: ONLINE", "// AUTH_LEVEL: MASTER_OWNER"]);

  const theme = {
    bg: '#010204', blue: '#38bdf8', purple: '#a78bfa', gold: '#fbbf24',
    border: '1px solid rgba(56, 189, 248, 0.12)', fontMono: '"JetBrains Mono", monospace'
  };

  const triggerBoot = () => {
    setBooting(true);
    let progress = 0;
    const interval = setInterval(() => {
      progress += 10;
      setBootProgress(progress);
      if (progress >= 100) {
        clearInterval(interval);
        setTimeout(() => { setBooting(false); setView('workspace'); }, 500);
      }
    }, 80);
  };

  // --- TWIN'S FIRST GENERATION ENGINE ---
  const handleExecuteBuild = () => {
    setIsGenerating(true);
    setConsoleLog(prev => [...prev, "> INITIATING_ARCHITECT_SEQUENCE...", "> TWIN: 'Constructing a premium interface...'"]);
    
    setTimeout(() => {
      // This is TWIN "producing" a real UI
      setPreviewContent(
        <div style={{ padding: '40px', textAlign: 'center', animation: 'fadeRender 0.8s ease-out', fontFamily: 'sans-serif' }}>
          <h2 style={{ color: '#0f172a', fontSize: '2rem', fontWeight: '800' }}>Generated by TWIN</h2>
          <p style={{ color: '#64748b' }}>This is a high-performance, resident-ready module.</p>
          <div style={{ marginTop: '30px', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '15px' }}>
            <div style={{ padding: '20px', borderRadius: '12px', background: '#f8fafc', border: '1px solid #e2e8f0' }}>
              <div style={{ fontSize: '1.5rem' }}>📈</div>
              <div style={{ fontWeight: 'bold', marginTop: '10px' }}>Analytics</div>
            </div>
            <div style={{ padding: '20px', borderRadius: '12px', background: '#f8fafc', border: '1px solid #e2e8f0' }}>
              <div style={{ fontSize: '1.5rem' }}>🔐</div>
              <div style={{ fontWeight: 'bold', marginTop: '10px' }}>Security</div>
            </div>
          </div>
          <button style={{ marginTop: '30px', width: '100%', padding: '15px', background: theme.blue, color: '#000', border: 'none', borderRadius: '8px', fontWeight: 'bold' }}>
            VIEW_LIVE_METRICS
          </button>
        </div>
      );
      setIsGenerating(false);
      setConsoleLog(prev => [...prev, "> RENDER_COMPLETE. 10% FEE SECURED."]);
    }, 2500);
  };

  const Workspace = () => (
    <div style={{ backgroundColor: theme.bg, color: '#fff', height: '100vh', display: 'flex', flexDirection: 'column', fontFamily: theme.fontMono }}>
      <style>{animationKeyframes}</style>
      
      {/* HEADER */}
      <div style={{ height: '65px', borderBottom: theme.border, display: 'flex', alignItems: 'center', padding: '0 25px', justifyContent: 'space-between', backgroundColor: '#000' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '15px' }}><span style={{ fontSize: '1.2rem', color: theme.blue }}>🪷</span><span style={{ fontWeight: 'bold', fontSize: '0.8rem', letterSpacing: '2px' }}>BLUE_LOTUS_CORE</span></div>
        <div style={{ fontSize: '0.7rem', color: theme.blue }}>STATUS: TWIN_MASTER_ACTIVE</div>
      </div>

      <div style={{ display: 'flex', flex: 1, overflow: 'hidden' }}>
        <div style={{ width: '450px', borderRight: theme.border, display: 'flex', flexDirection: 'column', backgroundColor: '#010204', padding: '20px' }}>
          <div style={{ flex: 1, backgroundColor: '#000', border: '1px solid #111827', padding: '15px', color: theme.blue, fontSize: '0.85rem', position: 'relative', overflowY: 'auto' }}>
            {consoleLog.map((line, i) => <div key={i} style={{ marginBottom: '5px' }}>{line}</div>)}
            {isGenerating && <div style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '2px', background: theme.blue, animation: 'scanline 2s linear infinite' }} />}
          </div>
          <textarea placeholder="Direct TWIN to build..." style={{ width: '100%', height: '80px', marginTop: '20px', padding: '15px', backgroundColor: '#0a0f1d', border: theme.border, borderRadius: '4px', color: '#fff', outline: 'none' }} />
          <button onClick={handleExecuteBuild} style={{ width: '100%', marginTop: '10px', padding: '15px', backgroundColor: theme.blue, color: '#000', fontWeight: '900', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>
            {isGenerating ? "ARCHITECTING..." : "EXECUTE_BUILD"}
          </button>
        </div>

        {/* PREVIEW WINDOW (This is where the magic happens) */}
        <div style={{ flex: 1, backgroundColor: '#020408', padding: '30px' }}>
          <div style={{ width: '100%', height: '100%', backgroundColor: '#fff', borderRadius: '4px', overflow: 'hidden', color: '#000' }}>
             {previewContent || (
               <div style={{ height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#cbd5e1', fontSize: '1rem' }}>
                 AWAITING_RENDER_COMMAND...
               </div>
             )}
          </div>
        </div>
      </div>
    </div>
  );

  if (booting) return <div style={{ backgroundColor: '#000', height: '100vh', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', color: theme.blue, fontFamily: theme.fontMono }}>INITIALIZING... {bootProgress}%</div>;

  return view === 'landing' ? (
    <div style={{ backgroundColor: theme.bg, color: '#fff', height: '100vh', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
      <h1 style={{ fontSize: '7rem', fontWeight: '900' }}><span style={{ color: theme.blue }}>Blue</span> Lotus</h1>
      <button onClick={triggerBoot} style={{ marginTop: '30px', padding: '20px 60px', background: 'none', border: `1px solid ${theme.blue}`, color: theme.blue, fontWeight: 'bold', cursor: 'pointer' }}>LAUNCH_CORE</button>
    </div>
  ) : <Workspace />;
}

export default App;
